### ISSUE TITLE
关于github robot功能讨论

### ISSUE THREAD

**Issue by yugasun** [yugasun/yuga-bot#2]
## 自动处理 issue

比如想要自动给 `issue` 贴 `label`, 我们必须讨论并定义一套 `划分规则`，比如issue内容中包含 `bug`等关键字，则自动贴 `bug`。

## 自动处理 PR

同样的，满足 `特定规则` 的，我们特定回复，然后自动操作。

以上问题，都是需要我们针对性的指定相关自动处理规则，现在的规则都是我个人YY出来的。但是这个规则不同的项目处理也会有区别，如何高效的提炼出一套较为通用的规则，需要进一步商讨，@xuexb，你有什么好的想法？

**Comment by xuexb** [comment]
先 mark 下, 本周末有些工作事情需要处理, 我也想想, 你也想想, 有任何想法都往这里贴~

**Comment by xuexb** [comment]
推送到远端 tag 后自动识别从上一个 tag 至今的 commit log 去发布一个 release note , 前提是需要定义 commit log 规范~

**Comment by xuexb** [comment]
发 PR 时自动 check PR 的标题是否包括: `Action: xxx` 这样, 否则评论让其修改~

**Comment by xuexb** [comment]
https://github.com/eggjs/egg/releases

**Comment by xuexb** [comment]
https://github.com/xuexb/github-bot
